// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { useState, useCallback, useMemo, useEffect, useRef, useContext, useReducer } from 'react';
  export { fakeBrowser } from 'wxt/testing';
  export { BNBCoinIcon, ChainCoinIcon } from '../components/Coins';
  export { Logo } from '../components/Logo';
  export { default as AxiomAPI, AxiomAPI, AxiomPairInfoResponse } from '../hooks/AxiomAPI';
  export { default as FlapAPI, FlapAPI } from '../hooks/FlapAPI';
  export { default as GmgnAPI, extractGmgnAuthData, GmgnAPI, MultiTokenInfoResponse, TokenCandle, TokenCandlesResponse, ApiUrlParams, SwapOrderRequest, SwapOrderResponse, BuyOrderParams, SellOrderParams, TokenCandlesParams, DailyProfit, DailyProfitResponse, DailyProfitParams } from '../hooks/GmgnAPI';
  export { TokenAPI, TokenAPI } from '../hooks/TokenAPI';
  export { loadContractAbi, useContractAbi, ContractAddress } from '../hooks/useContractAbi';
  export { encryptJson, decryptJson } from '../utils/crypto';
  export { defaultSettings } from '../utils/defaults';
  export { isHexPrivateKey, parseNumberLoose, normalizePriceValue, formatPriceValue, formatTime, formatBroadcastProvider } from '../utils/format';
  export { t, normalizeLocale, Locale } from '../utils/i18n';
  export { call } from '../utils/messaging';
  export { parseCurrentUrl, parseCurrentUrlFull, SiteInfo } from '../utils/sites';
  export { validateSettings } from '../utils/validate';
}
