// Generated by wxt
export {}
declare global {
  const AxiomAPI: typeof import('D:/projects/blockchain/opensource/dagobang-extention/hooks/AxiomAPI').default
  const BNBCoinIcon: typeof import('D:/projects/blockchain/opensource/dagobang-extention/components/Coins').BNBCoinIcon
  const ChainCoinIcon: typeof import('D:/projects/blockchain/opensource/dagobang-extention/components/Coins').ChainCoinIcon
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DEFAULT_SOLANA_TIP_PRESET_VALUES: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/solanaTip').DEFAULT_SOLANA_TIP_PRESET_VALUES
  const DexScreenerAPI: typeof import('D:/projects/blockchain/opensource/dagobang-extention/hooks/DexScreenerAPI').default
  const ETHCoinIcon: typeof import('D:/projects/blockchain/opensource/dagobang-extention/components/Coins').ETHCoinIcon
  const FlapAPI: typeof import('D:/projects/blockchain/opensource/dagobang-extention/hooks/FlapAPI').default
  const GmgnAPI: typeof import('D:/projects/blockchain/opensource/dagobang-extention/hooks/GmgnAPI').default
  const HYPECoinIcon: typeof import('D:/projects/blockchain/opensource/dagobang-extention/components/Coins').HYPECoinIcon
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const Logo: typeof import('D:/projects/blockchain/opensource/dagobang-extention/components/Logo').Logo
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const SOLCoinIcon: typeof import('D:/projects/blockchain/opensource/dagobang-extention/components/Coins').SOLCoinIcon
  const SymbolCoinIcon: typeof import('D:/projects/blockchain/opensource/dagobang-extention/components/Coins').SymbolCoinIcon
  const TokenAPI: typeof import('D:/projects/blockchain/opensource/dagobang-extention/hooks/TokenAPI').TokenAPI
  const USDCCoinIcon: typeof import('D:/projects/blockchain/opensource/dagobang-extention/components/Coins').USDCCoinIcon
  const asAddress: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').asAddress
  const browser: typeof import('wxt/browser').browser
  const call: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/messaging').call
  const classifyBroadcastError: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/txErrorClassify').classifyBroadcastError
  const classifyFlapRoute: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/flap').classifyFlapRoute
  const collectErrorText: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/txErrorClassify').collectErrorText
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const decryptJson: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/crypto').decryptJson
  const defaultSettings: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/defaults').defaultSettings
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const encryptJson: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/crypto').encryptJson
  const extractFirstFromObject: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractFirstFromObject
  const extractGmgnAuthData: typeof import('D:/projects/blockchain/opensource/dagobang-extention/hooks/GmgnAPI').extractGmgnAuthData
  const extractGmgnTweetText: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractGmgnTweetText
  const extractGmgnUserFields: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractGmgnUserFields
  const extractGmgnWsConnectionInfo: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractGmgnWsConnectionInfo
  const extractMedia: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractMedia
  const extractNextNonceHintFromText: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/txErrorClassify').extractNextNonceHintFromText
  const extractNumber: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractNumber
  const extractPublicBroadcastCreates: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractPublicBroadcastCreates
  const extractText: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractText
  const extractTimestampMs: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractTimestampMs
  const extractTokenAddress: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractTokenAddress
  const extractTokenAddresses: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractTokenAddresses
  const extractTweetId: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractTweetId
  const extractUser: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').extractUser
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const formatAgeShort: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').formatAgeShort
  const formatBnbAmount: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').formatBnbAmount
  const formatBroadcastProvider: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').formatBroadcastProvider
  const formatCompactNumber: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').formatCompactNumber
  const formatCountShort: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').formatCountShort
  const formatPriceValue: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').formatPriceValue
  const formatRpcEndpointLabel: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').formatRpcEndpointLabel
  const formatShortAddress: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').formatShortAddress
  const formatTime: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').formatTime
  const getDexPoolPrefer: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/dexUtils').getDexPoolPrefer
  const getNonceErrorKindFromText: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/txErrorClassify').getNonceErrorKindFromText
  const getRandomSolanaTipRecipient: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/solanaTip').getRandomSolanaTipRecipient
  const getSolanaTipAccounts: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/solanaTip').getSolanaTipAccounts
  const getSolanaTipMinimumNative: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/solanaTip').getSolanaTipMinimumNative
  const getSolanaTipPresetValue: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/solanaTip').getSolanaTipPresetValue
  const getSolanaTipProviderLabel: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/solanaTip').getSolanaTipProviderLabel
  const hasConfirmedFlapLaunchpadIdentity: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/flap').hasConfirmedFlapLaunchpadIdentity
  const hasConfirmedFlapOuterRoute: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/flap').hasConfirmedFlapOuterRoute
  const hasConfirmedFlapStocksIdentity: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/flap').hasConfirmedFlapStocksIdentity
  const hasNonTerminalFlapOuterQuote: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/flap').hasNonTerminalFlapOuterQuote
  const inferLaunchpadFamilyByAddress: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/launchpadFamily').inferLaunchpadFamilyByAddress
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isAllowanceLikeText: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/txErrorClassify').isAllowanceLikeText
  const isFlapSuffixAddress: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/launchpadFamily').isFlapSuffixAddress
  const isFourMemeSuffixAddress: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/launchpadFamily').isFourMemeSuffixAddress
  const isHexPrivateKey: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').isHexPrivateKey
  const isInFlightLimitLikeText: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/txErrorClassify').isInFlightLimitLikeText
  const isObject: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').isObject
  const isUsableFlapDexPoolAddress: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/flap').isUsableFlapDexPoolAddress
  const loadContractAbi: typeof import('D:/projects/blockchain/opensource/dagobang-extention/hooks/useContractAbi').loadContractAbi
  const navigateToUrl: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/sites').navigateToUrl
  const normalizeFlapLaunchpadStatus: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/flap').normalizeFlapLaunchpadStatus
  const normalizeGmgnChainName: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').normalizeGmgnChainName
  const normalizeHexPrivateKey: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').normalizeHexPrivateKey
  const normalizeInlineWebpData: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').normalizeInlineWebpData
  const normalizeLocale: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/i18n').normalizeLocale
  const normalizeNewPoolTokenData: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').normalizeNewPoolTokenData
  const normalizePercentValue: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/value').normalizePercentValue
  const normalizePriceValue: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').normalizePriceValue
  const normalizePublicTokenData: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').normalizePublicTokenData
  const normalizeTokenAddressKey: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').normalizeTokenAddressKey
  const normalizeTokenPageTokenData: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').normalizeTokenPageTokenData
  const normalizeTokenStatTokenData: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').normalizeTokenStatTokenData
  const normalizeTrenchesTokenData: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').normalizeTrenchesTokenData
  const parseCurrentUrl: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/sites').parseCurrentUrl
  const parseCurrentUrlFull: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/sites').parseCurrentUrlFull
  const parseGmgnEnvelope: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').parseGmgnEnvelope
  const parseGweiToWei: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/dexUtils').parseGweiToWei
  const parseNumberLoose: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/format').parseNumberLoose
  const parsePlatformTokenLink: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/sites').parsePlatformTokenLink
  const pickFiniteNumber: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/value').pickFiniteNumber
  const pickMaxFiniteNumber: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/value').pickMaxFiniteNumber
  const pickMaxPercentValue: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/value').pickMaxPercentValue
  const resolveEnabledSolanaSwqosProviderTypes: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/solanaTip').resolveEnabledSolanaSwqosProviderTypes
  const resolveFlapPlatform: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/flap').resolveFlapPlatform
  const resolveFlapPlatformByQuoteLineage: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/flap').resolveFlapPlatformByQuoteLineage
  const resolveSingleEnabledSolanaTipProvider: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/solanaTip').resolveSingleEnabledSolanaTipProvider
  const resolveSolanaTipConfig: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/solanaTip').resolveSolanaTipConfig
  const resolveTokenLaunchpadPlatform: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/launchpadFamily').resolveTokenLaunchpadPlatform
  const resolveTrenchesStageByFid: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').resolveTrenchesStageByFid
  const shouldUseMergedTokenValue: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').shouldUseMergedTokenValue
  const storage: typeof import('wxt/utils/storage').storage
  const t: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/i18n').t
  const toArrayPayload: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs').toArrayPayload
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useContractAbi: typeof import('D:/projects/blockchain/opensource/dagobang-extention/hooks/useContractAbi').useContractAbi
  const useEffect: typeof import('react').useEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useTradeSuccessSound: typeof import('D:/projects/blockchain/opensource/dagobang-extention/hooks/useTradeSuccessSound').useTradeSuccessSound
  const validateSettings: typeof import('D:/projects/blockchain/opensource/dagobang-extention/utils/validate').validateSettings
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { AxiomAPI, AxiomPairInfoResponse } from 'D:/projects/blockchain/opensource/dagobang-extention/hooks/AxiomAPI'
  import('D:/projects/blockchain/opensource/dagobang-extention/hooks/AxiomAPI')
  // @ts-ignore
  export type { DexScreenerAPI, DexScreenerTokenRef, DexScreenerPair } from 'D:/projects/blockchain/opensource/dagobang-extention/hooks/DexScreenerAPI'
  import('D:/projects/blockchain/opensource/dagobang-extention/hooks/DexScreenerAPI')
  // @ts-ignore
  export type { FlapAPI, FlapCoinApiResponse } from 'D:/projects/blockchain/opensource/dagobang-extention/hooks/FlapAPI'
  import('D:/projects/blockchain/opensource/dagobang-extention/hooks/FlapAPI')
  // @ts-ignore
  export type { GmgnAPI, MultiTokenInfoResponse, GmgnSearchTokenItem, GmgnTokenHolding, GmgnPageFetchRequest, TokenCandle, TokenCandlesResponse, ApiUrlParams, SwapOrderRequest, SwapOrderResponse, BuyOrderParams, SellOrderParams, TokenCandlesParams, DailyProfit, DailyProfitResponse, DailyProfitParams, TokenHoldingDetail, TokenHoldingDetailResponse } from 'D:/projects/blockchain/opensource/dagobang-extention/hooks/GmgnAPI'
  import('D:/projects/blockchain/opensource/dagobang-extention/hooks/GmgnAPI')
  // @ts-ignore
  export type { TokenAPI } from 'D:/projects/blockchain/opensource/dagobang-extention/hooks/TokenAPI'
  import('D:/projects/blockchain/opensource/dagobang-extention/hooks/TokenAPI')
  // @ts-ignore
  export type { ContractAddress } from 'D:/projects/blockchain/opensource/dagobang-extention/hooks/useContractAbi'
  import('D:/projects/blockchain/opensource/dagobang-extention/hooks/useContractAbi')
  // @ts-ignore
  export type { TrenchesStage } from 'D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs'
  import('D:/projects/blockchain/opensource/dagobang-extention/utils/gmgnWs')
  // @ts-ignore
  export type { Locale } from 'D:/projects/blockchain/opensource/dagobang-extention/utils/i18n'
  import('D:/projects/blockchain/opensource/dagobang-extention/utils/i18n')
  // @ts-ignore
  export type { LaunchpadFamily } from 'D:/projects/blockchain/opensource/dagobang-extention/utils/launchpadFamily'
  import('D:/projects/blockchain/opensource/dagobang-extention/utils/launchpadFamily')
  // @ts-ignore
  export type { SiteInfo } from 'D:/projects/blockchain/opensource/dagobang-extention/utils/sites'
  import('D:/projects/blockchain/opensource/dagobang-extention/utils/sites')
  // @ts-ignore
  export type { BroadcastErrorClass } from 'D:/projects/blockchain/opensource/dagobang-extention/utils/txErrorClassify'
  import('D:/projects/blockchain/opensource/dagobang-extention/utils/txErrorClassify')
}
