import type { Settings, ChainSettings, AutoTradeConfig, GasGweiConfig, AdvancedAutoSellConfig } from '../types/extention';

const DEFAULT_GAS_GWEI: GasGweiConfig = {
  slow: '0.06',
  standard: '0.12',
  fast: '1',
  turbo: '5',
};

const BSC_MAINNET: ChainSettings = {
  rpcUrls: [
    'https://0.48.club',
    'https://1rpc.io/bnb',
    'https://bsc.rpc.blxrbdn.com',
    'https://bsc-dataseed.ninicoin.io',
    'https://bsc-dataseed.defibit.io',
    'https://bsc-dataseed-public.bnbchain.org',
    'https://bscrpc.pancakeswap.finance',
  ],
  protectedRpcUrls: [
    'https://bscrpc.pancakeswap.finance',
    'https://pancake.rpc.48.club',
    'https://four.rpc.48.club',
    'https://debot.bsc.blockrazor.xyz'
  ],
  antiMev: true,
  gasPreset: 'standard',
  buyGasPreset: 'standard',
  sellGasPreset: 'standard',
  executionMode: 'default',
  slippageBps: 4000,
  deadlineSeconds: 60,
  buyPresets: ['0.1', '0.5', '1.0', '2.0'],
  sellPresets: ['25', '50', '75', '100'],
  buyGasGwei: DEFAULT_GAS_GWEI,
  sellGasGwei: DEFAULT_GAS_GWEI,
  approveGasGwei: '0.06',
};

const DEFAULT_AUTOTRADE: AutoTradeConfig = {
  takeProfitMultiple: '2',
  stopLossMultiple: '0.5',
  maxHoldMinutes: '',
  wsMonitorEnabled: false,
  triggerSound: {
    enabled: true,
    preset: 'Boom',
  },
  twitterSnipe: {
    enabled: true,
    dryRun: true,
    autoSellEnabled: true,
    buyAmountBnb: '0.01',
    buyNewCaCount: '1',
    buyOgCount: '0',
    minMarketCapUsd: '',
    maxMarketCapUsd: '',
    minHolders: '',
    maxHolders: '',
    minKol: '',
    maxKol: '',
    minTickerLen: '',
    maxTickerLen: '',
    minTokenAgeSeconds: '',
    maxTokenAgeSeconds: '',
    minTweetAgeSeconds: '',
    maxTweetAgeSeconds: '',
    minDevHoldPercent: '',
    maxDevHoldPercent: '',
    blockIfDevSell: true,
    wsConfirmEnabled: true,
    wsConfirmWindowMs: '5000',
    wsConfirmMinMcapChangePct: '2',
    wsConfirmMinHoldersDelta: '0',
    wsConfirmMinBuySellRatio: '1',
    wsConfirmMinNetBuy24hUsd: '0',
    wsConfirmMinVol24hUsd: '0',
    wsConfirmMinSmartMoney: '0',
    stagedEntryEnabled: false,
    stagedEntryScoutPercent: '25',
    stagedEntryMinDelayMs: '3000',
    stagedEntryMaxDelayMs: '15000',
    stagedEntryMaxDrawdownPct: '8',
    timeStopEnabled: false,
    timeStopSeconds: '30',
    timeStopMinPnlPct: '-3',
    timeStopSellPercent: '100',
    rapidExitEnabled: true,
    rapidTakeProfitPct: '12',
    rapidStopLossPct: '-7',
    rapidMaxHoldSeconds: '20',
    rapidTrailActivatePct: '8',
    rapidTrailDropPct: '4',
    rapidMinHoldMsForTakeProfit: '1200',
    rapidMinHoldMsForStopLoss: '800',
    rapidMinHoldMsForTrail: '1800',
    rapidSellPercent: '100',
    rapidByTweetTypeEnabled: true,
    rapidByType: {
      tweet: { takeProfitPct: '11', stopLossPct: '-5.5', maxHoldSeconds: '14', trailActivatePct: '7', trailDropPct: '3.5' },
      reply: { takeProfitPct: '7', stopLossPct: '-4', maxHoldSeconds: '9', trailActivatePct: '5', trailDropPct: '3' },
      quote: { takeProfitPct: '10', stopLossPct: '-5', maxHoldSeconds: '12', trailActivatePct: '6', trailDropPct: '3.2' },
      retweet: { takeProfitPct: '10', stopLossPct: '-5', maxHoldSeconds: '12', trailActivatePct: '6', trailDropPct: '3.2' },
      follow: { takeProfitPct: '8', stopLossPct: '-4.5', maxHoldSeconds: '10', trailActivatePct: '5.5', trailDropPct: '3' },
    },
    deleteTweetSellPercent: '',
    deleteTweetPlaySound: true,
    deleteTweetSoundPreset: 'Handgun',
    targetUsers: [],
    interactionTypes: ['tweet', 'reply', 'quote', 'retweet', 'follow'],
    presets: [
      {
        id: 'preset-flow',
        name: '流水盘',
        strategy: {
          enabled: true,
          dryRun: true,
          autoSellEnabled: true,
          buyAmountBnb: '0.006',
          buyNewCaCount: '1',
          buyOgCount: '0',
          minMarketCapUsd: '',
          maxMarketCapUsd: '800000',
          minHolders: '20',
          maxHolders: '',
          minKol: '',
          maxKol: '',
          minTickerLen: '',
          maxTickerLen: '',
          minTokenAgeSeconds: '',
          maxTokenAgeSeconds: '',
          minTweetAgeSeconds: '',
          maxTweetAgeSeconds: '240',
          minDevHoldPercent: '',
          maxDevHoldPercent: '20',
          blockIfDevSell: true,
          wsConfirmEnabled: true,
          wsConfirmWindowMs: '5000',
          wsConfirmMinMcapChangePct: '1.5',
          wsConfirmMinHoldersDelta: '0',
          wsConfirmMinBuySellRatio: '1',
          wsConfirmMinNetBuy24hUsd: '0',
          wsConfirmMinVol24hUsd: '0',
          wsConfirmMinSmartMoney: '0',
          stagedEntryEnabled: false,
          stagedEntryScoutPercent: '25',
          stagedEntryMinDelayMs: '3000',
          stagedEntryMaxDelayMs: '15000',
          stagedEntryMaxDrawdownPct: '8',
          timeStopEnabled: true,
          timeStopSeconds: '6',
          timeStopMinPnlPct: '-12',
          timeStopSellPercent: '100',
          rapidExitEnabled: true,
          rapidTakeProfitPct: '10',
          rapidStopLossPct: '-6',
          rapidMaxHoldSeconds: '16',
          rapidTrailActivatePct: '7',
          rapidTrailDropPct: '4',
          rapidMinHoldMsForTakeProfit: '900',
          rapidMinHoldMsForStopLoss: '700',
          rapidMinHoldMsForTrail: '1600',
          rapidSellPercent: '100',
          rapidByTweetTypeEnabled: true,
          rapidByType: {
            tweet: { takeProfitPct: '10', stopLossPct: '-5.5', maxHoldSeconds: '12', trailActivatePct: '6.5', trailDropPct: '3.2' },
            reply: { takeProfitPct: '6.5', stopLossPct: '-3.8', maxHoldSeconds: '8', trailActivatePct: '4.8', trailDropPct: '2.8' },
            quote: { takeProfitPct: '9', stopLossPct: '-4.8', maxHoldSeconds: '10', trailActivatePct: '6', trailDropPct: '3' },
            retweet: { takeProfitPct: '9', stopLossPct: '-4.8', maxHoldSeconds: '10', trailActivatePct: '6', trailDropPct: '3' },
            follow: { takeProfitPct: '7', stopLossPct: '-4.2', maxHoldSeconds: '9', trailActivatePct: '5', trailDropPct: '2.8' },
          },
          deleteTweetSellPercent: '',
          deleteTweetPlaySound: true,
          deleteTweetSoundPreset: 'Handgun',
          targetUsers: [],
          interactionTypes: ['tweet', 'reply', 'quote', 'retweet', 'follow'],
        },
      },
      {
        id: 'preset-trend',
        name: '趋势盘',
        strategy: {
          enabled: true,
          dryRun: true,
          autoSellEnabled: true,
          buyAmountBnb: '0.008',
          buyNewCaCount: '2',
          buyOgCount: '0',
          minMarketCapUsd: '120000',
          maxMarketCapUsd: '',
          minHolders: '40',
          maxHolders: '',
          minKol: '',
          maxKol: '',
          minTickerLen: '',
          maxTickerLen: '',
          minTokenAgeSeconds: '',
          maxTokenAgeSeconds: '',
          minTweetAgeSeconds: '',
          maxTweetAgeSeconds: '',
          minDevHoldPercent: '',
          maxDevHoldPercent: '35',
          blockIfDevSell: true,
          wsConfirmEnabled: true,
          wsConfirmWindowMs: '7000',
          wsConfirmMinMcapChangePct: '3',
          wsConfirmMinHoldersDelta: '0',
          wsConfirmMinBuySellRatio: '1.2',
          wsConfirmMinNetBuy24hUsd: '0',
          wsConfirmMinVol24hUsd: '0',
          wsConfirmMinSmartMoney: '0',
          stagedEntryEnabled: false,
          stagedEntryScoutPercent: '35',
          stagedEntryMinDelayMs: '3500',
          stagedEntryMaxDelayMs: '18000',
          stagedEntryMaxDrawdownPct: '10',
          timeStopEnabled: false,
          timeStopSeconds: '30',
          timeStopMinPnlPct: '-8',
          timeStopSellPercent: '100',
          rapidExitEnabled: true,
          rapidTakeProfitPct: '15',
          rapidStopLossPct: '-8',
          rapidMaxHoldSeconds: '30',
          rapidTrailActivatePct: '10',
          rapidTrailDropPct: '5',
          rapidMinHoldMsForTakeProfit: '1400',
          rapidMinHoldMsForStopLoss: '900',
          rapidMinHoldMsForTrail: '2000',
          rapidSellPercent: '100',
          rapidByTweetTypeEnabled: true,
          rapidByType: {
            tweet: { takeProfitPct: '14', stopLossPct: '-7.5', maxHoldSeconds: '20', trailActivatePct: '9', trailDropPct: '4.5' },
            reply: { takeProfitPct: '9', stopLossPct: '-5.2', maxHoldSeconds: '13', trailActivatePct: '7', trailDropPct: '3.5' },
            quote: { takeProfitPct: '12', stopLossPct: '-6.5', maxHoldSeconds: '17', trailActivatePct: '8', trailDropPct: '4' },
            retweet: { takeProfitPct: '12', stopLossPct: '-6.5', maxHoldSeconds: '17', trailActivatePct: '8', trailDropPct: '4' },
            follow: { takeProfitPct: '10', stopLossPct: '-5.8', maxHoldSeconds: '15', trailActivatePct: '7.5', trailDropPct: '3.8' },
          },
          deleteTweetSellPercent: '',
          deleteTweetPlaySound: true,
          deleteTweetSoundPreset: 'Handgun',
          targetUsers: [],
          interactionTypes: ['tweet', 'reply', 'quote', 'retweet', 'follow'],
        },
      },
    ],
    activePresetId: 'preset-flow',
  },
};

const DEFAULT_ADVANCED_AUTO_SELL: AdvancedAutoSellConfig = {
  enabled: false,
  rules: [
    { id: 'tp_100', type: 'take_profit', triggerPercent: 100, sellPercent: 50 },
    { id: 'tp_300', type: 'take_profit', triggerPercent: 300, sellPercent: 50 },
    { id: 'sl_50', type: 'stop_loss', triggerPercent: -50, sellPercent: 100 },
  ],
  trailingStop: {
    enabled: false,
    callbackPercent: 15,
    sellPercent: 70,
    activationMode: 'after_last_take_profit',
  },
};

export function defaultSettings(): Settings {
  return {
    chainId: 56,
    chains: {
      56: BSC_MAINNET,
    },
    autoLockSeconds: 30 * 60, // 30 minutes
    locale: 'zh_CN',
    accountAliases: {},
    toastPosition: 'top-center',
    seedreamApiKey: '',
    bloxrouteAuthHeader: '',
    quickBuy1Bnb: '0',
    quickBuy2Bnb: '0',
    keyboardShortcutsEnabled: false,
    tradeSuccessSoundEnabled: false,
    tradeSuccessSoundPresetBuy: 'Bell',
    tradeSuccessSoundPresetSell: 'Coins',
    tradeSuccessSoundVolume: 60,
    limitOrderScanIntervalMs: 3000,
    tokenBalancePollIntervalMs: 2000,
    ui: {
      showToolbar: true,
      limitTradePanelOnlyOnTokenPage: false,
    },
    autoTrade: DEFAULT_AUTOTRADE,
    advancedAutoSell: DEFAULT_ADVANCED_AUTO_SELL,
  };
}
