import type { Settings, ChainSettings, AutoTradeConfig, GasGweiConfig, AdvancedAutoSellConfig } from '../types/extention';

const DEFAULT_GAS_GWEI: GasGweiConfig = {
  slow: '0.06',
  standard: '0.12',
  fast: '1',
  turbo: '5',
};

const DEFAULT_PRIORITY_FEE_PRESETS = {
  none: '0',
  slow: '0.000025',
  standard: '0.00004',
  fast: '0.0001',
} as const;

const BSC_MAINNET: ChainSettings = {
  rpcUrls: [
    'https://0.48.club',
    'https://1rpc.io/bnb',
    'https://bsc.rpc.blxrbdn.com',
    'https://bsc-dataseed.ninicoin.io',
    'https://bsc-dataseed.defibit.io',
    'https://bsc-dataseed-public.bnbchain.org',
    'https://bscrpc.pancakeswap.finance',
  ],
  protectedRpcUrls: [
    'https://bscrpc.pancakeswap.finance',
    'https://pancake.rpc.48.club',
    'https://four.rpc.48.club',
    'https://debot.bsc.blockrazor.xyz'
  ],
  protectedRpcUrlsBuy: [
    'https://bscrpc.pancakeswap.finance',
    'https://pancake.rpc.48.club',
    'https://four.rpc.48.club',
    'https://debot.bsc.blockrazor.xyz'
  ],
  protectedRpcUrlsSell: [
    'https://bscrpc.pancakeswap.finance',
    'https://pancake.rpc.48.club',
    'https://four.rpc.48.club',
    'https://debot.bsc.blockrazor.xyz'
  ],
  antiMev: true,
  gasPreset: 'standard',
  buyGasPreset: 'standard',
  sellGasPreset: 'standard',
  executionMode: 'default',
  slippageBps: 4000,
  deadlineSeconds: 60,
  buyPresets: ['0.1', '0.5', '1.0', '2.0'],
  sellPresets: ['25', '50', '75', '100'],
  buyGasGwei: DEFAULT_GAS_GWEI,
  sellGasGwei: DEFAULT_GAS_GWEI,
  approveGasGwei: '0.06',
  buyPriorityFeePreset: 'standard',
  sellPriorityFeePreset: 'standard',
  buyPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  sellPriorityFeePresets: DEFAULT_PRIORITY_FEE_PRESETS,
  bloxrouteBuyEnabled: true,
  bloxrouteSellEnabled: true,
};

const DEFAULT_AUTOTRADE: AutoTradeConfig = {
  takeProfitMultiple: '2',
  stopLossMultiple: '0.5',
  maxHoldMinutes: '',
  wsMonitorEnabled: false,
  triggerSound: {
    enabled: true,
    preset: 'Boom',
  },
  twitterSnipe: {
    enabled: true,
    dryRun: true,
    dryRunBuyDelayMs: '1000',
    dryRunSellDelayMs: '2000',
    autoSellEnabled: true,
    buyAmountBnb: '0.01',
    buyNewCaCount: '1',
    buyOgCount: '0',
    minMarketCapUsd: '',
    maxMarketCapUsd: '',
    minHolders: '',
    maxHolders: '',
    minKol: '',
    maxKol: '',
    minTickerLen: '',
    maxTickerLen: '',
    minTokenAgeSeconds: '',
    maxTokenAgeSeconds: '',
    minTweetAgeSeconds: '',
    maxTweetAgeSeconds: '',
    minDevHoldPercent: '',
    maxDevHoldPercent: '',
    blockIfDevSell: true,
    wsConfirmEnabled: true,
    wsConfirmWindowMs: '5000',
    wsConfirmMinMcapChangePct: '2',
    wsConfirmMinHoldersDelta: '0',
    wsConfirmMinBuySellRatio: '1',
    wsConfirmMinNetBuy24hUsd: '0',
    wsConfirmMinVol24hUsd: '0',
    wsConfirmMinSmartMoney: '0',
    rapidExitEnabled: true,
    rapidHoldSeconds: '60',
    rapidEvalStepSec: '5',
    rapidLookbackSec: '6',
    rapidEmergencyConfirmSteps: '2',
    rapidEmergencyStopLossPct: '-40',
    rapidRouteCut1Pct: '-10',
    rapidRouteCut2Pct: '4',
    rapidExit20Sec: '20',
    rapidStage1Sec: '3',
    rapidStage2Sec: '6',
    rapidStage3Sec: '8',
    rapidStage4Sec: '10',
    rapidStage1ProfitPct: '4',
    rapidStage2ProfitPct: '8',
    rapidStage3ProfitPct: '12',
    rapidStage4ProfitPct: '15',
    rapidStage1SellPct: '20',
    rapidStage2SellPct: '25',
    rapidStage3SellPct: '25',
    rapidStage4SellPct: '10',
    rapidRunnerArmProfitPct: '8',
    rapidRunnerPeakCut1Pct: '6',
    rapidRunnerPeakCut2Pct: '40',
    rapidRunnerDrawdown1Pct: '0.2',
    rapidRunnerDrawdown2Pct: '0.5',
    rapidRunnerDrawdown3Pct: '10',
    deleteTweetSellPercent: '',
    deleteTweetPlaySound: true,
    deleteTweetSoundPreset: 'Handgun',
    targetUsers: [],
    interactionTypes: ['tweet', 'reply', 'quote', 'retweet', 'follow'],
    presets: [
      {
        id: 'preset-flow',
        name: '流水盘',
        strategy: {
          enabled: true,
          dryRun: true,
          dryRunBuyDelayMs: '1000',
          dryRunSellDelayMs: '2000',
          autoSellEnabled: true,
          buyAmountBnb: '0.006',
          buyNewCaCount: '1',
          buyOgCount: '0',
          minMarketCapUsd: '',
          maxMarketCapUsd: '800000',
          minHolders: '20',
          maxHolders: '',
          minKol: '',
          maxKol: '',
          minTickerLen: '',
          maxTickerLen: '',
          minTokenAgeSeconds: '',
          maxTokenAgeSeconds: '',
          minTweetAgeSeconds: '',
          maxTweetAgeSeconds: '240',
          minDevHoldPercent: '',
          maxDevHoldPercent: '20',
          blockIfDevSell: true,
          wsConfirmEnabled: true,
          wsConfirmWindowMs: '5000',
          wsConfirmMinMcapChangePct: '1.5',
          wsConfirmMinHoldersDelta: '0',
          wsConfirmMinBuySellRatio: '1',
          wsConfirmMinNetBuy24hUsd: '0',
          wsConfirmMinVol24hUsd: '0',
          wsConfirmMinSmartMoney: '0',
          rapidExitEnabled: true,
          rapidHoldSeconds: '60',
          rapidEvalStepSec: '5',
          rapidLookbackSec: '6',
          rapidEmergencyConfirmSteps: '2',
          rapidEmergencyStopLossPct: '-40',
          rapidRouteCut1Pct: '-10',
          rapidRouteCut2Pct: '4',
          rapidExit20Sec: '20',
          rapidStage1Sec: '3',
          rapidStage2Sec: '6',
          rapidStage3Sec: '8',
          rapidStage4Sec: '10',
          rapidStage1ProfitPct: '4',
          rapidStage2ProfitPct: '8',
          rapidStage3ProfitPct: '12',
          rapidStage4ProfitPct: '15',
          rapidStage1SellPct: '20',
          rapidStage2SellPct: '25',
          rapidStage3SellPct: '25',
          rapidStage4SellPct: '10',
          rapidRunnerArmProfitPct: '8',
          rapidRunnerPeakCut1Pct: '6',
          rapidRunnerPeakCut2Pct: '40',
          rapidRunnerDrawdown1Pct: '0.2',
          rapidRunnerDrawdown2Pct: '0.5',
          rapidRunnerDrawdown3Pct: '10',
          deleteTweetSellPercent: '',
          deleteTweetPlaySound: true,
          deleteTweetSoundPreset: 'Handgun',
          targetUsers: [],
          interactionTypes: ['tweet', 'reply', 'quote', 'retweet', 'follow'],
        },
      },
      {
        id: 'preset-trend',
        name: '趋势盘',
        strategy: {
          enabled: true,
          dryRun: true,
          dryRunBuyDelayMs: '1000',
          dryRunSellDelayMs: '2000',
          autoSellEnabled: true,
          buyAmountBnb: '0.008',
          buyNewCaCount: '2',
          buyOgCount: '0',
          minMarketCapUsd: '120000',
          maxMarketCapUsd: '',
          minHolders: '40',
          maxHolders: '',
          minKol: '',
          maxKol: '',
          minTickerLen: '',
          maxTickerLen: '',
          minTokenAgeSeconds: '',
          maxTokenAgeSeconds: '',
          minTweetAgeSeconds: '',
          maxTweetAgeSeconds: '',
          minDevHoldPercent: '',
          maxDevHoldPercent: '35',
          blockIfDevSell: true,
          wsConfirmEnabled: true,
          wsConfirmWindowMs: '7000',
          wsConfirmMinMcapChangePct: '3',
          wsConfirmMinHoldersDelta: '0',
          wsConfirmMinBuySellRatio: '1.2',
          wsConfirmMinNetBuy24hUsd: '0',
          wsConfirmMinVol24hUsd: '0',
          wsConfirmMinSmartMoney: '0',
          rapidExitEnabled: true,
          rapidHoldSeconds: '60',
          rapidEvalStepSec: '5',
          rapidLookbackSec: '6',
          rapidEmergencyConfirmSteps: '2',
          rapidEmergencyStopLossPct: '-40',
          rapidRouteCut1Pct: '-10',
          rapidRouteCut2Pct: '4',
          rapidExit20Sec: '20',
          rapidStage1Sec: '3',
          rapidStage2Sec: '6',
          rapidStage3Sec: '8',
          rapidStage4Sec: '10',
          rapidStage1ProfitPct: '4',
          rapidStage2ProfitPct: '8',
          rapidStage3ProfitPct: '12',
          rapidStage4ProfitPct: '15',
          rapidStage1SellPct: '20',
          rapidStage2SellPct: '25',
          rapidStage3SellPct: '25',
          rapidStage4SellPct: '10',
          rapidRunnerArmProfitPct: '8',
          rapidRunnerPeakCut1Pct: '6',
          rapidRunnerPeakCut2Pct: '40',
          rapidRunnerDrawdown1Pct: '0.2',
          rapidRunnerDrawdown2Pct: '0.5',
          rapidRunnerDrawdown3Pct: '10',
          deleteTweetSellPercent: '',
          deleteTweetPlaySound: true,
          deleteTweetSoundPreset: 'Handgun',
          targetUsers: [],
          interactionTypes: ['tweet', 'reply', 'quote', 'retweet', 'follow'],
        },
      },
    ],
    activePresetId: 'preset-flow',
  },
  tokenSnipe: {
    enabled: true,
    targetUsers: [],
    playSound: true,
    soundPreset: 'Boom',
    tasks: [],
  },
};

const DEFAULT_ADVANCED_AUTO_SELL: AdvancedAutoSellConfig = {
  enabled: false,
  rules: [
    { id: 'tp_100', type: 'take_profit', triggerPercent: 100, sellPercent: 50 },
    { id: 'tp_300', type: 'take_profit', triggerPercent: 300, sellPercent: 50 },
    { id: 'sl_50', type: 'stop_loss', triggerPercent: -50, sellPercent: 100 },
  ],
  trailingStop: {
    enabled: false,
    callbackPercent: 15,
    sellPercent: 70,
    activationMode: 'after_last_take_profit',
  },
};

export function defaultSettings(): Settings {
  return {
    chainId: 56,
    chains: {
      56: BSC_MAINNET,
    },
    autoLockSeconds: 30 * 60, // 30 minutes
    locale: 'zh_CN',
    accountAliases: {},
    toastPosition: 'top-center',
    seedreamApiKey: '',
    bloxrouteAuthHeader: '',
    quickBuy1Bnb: '0',
    quickBuy2Bnb: '0',
    keyboardShortcutsEnabled: false,
    tradeSuccessSoundEnabled: false,
    tradeSuccessSoundPresetBuy: 'Bell',
    tradeSuccessSoundPresetSell: 'Coins',
    tradeSuccessSoundVolume: 60,
    limitOrderScanIntervalMs: 3000,
    tokenBalancePollIntervalMs: 2000,
    ui: {
      showToolbar: true,
      limitTradePanelOnlyOnTokenPage: false,
    },
    telegram: {
      enabled: false,
      botToken: '',
      chatId: '',
      userId: '',
      enforceUserId: false,
      pollIntervalMs: 2000,
      notifyTradeSubmitted: true,
      notifyTradeSuccess: true,
      notifyTradeRetrying: true,
      notifyLimitOrder: true,
      notifyQuickTrade: true,
    },
    autoTrade: DEFAULT_AUTOTRADE,
    advancedAutoSell: DEFAULT_ADVANCED_AUTO_SELL,
  };
}
